chapter_writing:
  description: >
    Draft each chapter from the outline, seamlessly integrating character arcs, world details, and pacing cues. Produce clear, compelling scenes with strong hooks and effective scene/chapter transitions.
  expected_output: >
    A complete first-draft manuscript, with all chapters structured and written for further editing.
  agent: chapter_writer
  output_file: draft/first_draft_ms.md
  markdown: true

scene_enhancement:
  description: >
    Review all scenes for emotional depth, vivid description, atmosphere, and dialogue authenticity. Raise the immersive quality and strengthen reader engagement for every scene block.
  expected_output: >
    An enhanced manuscript with improved dialogue, more resonant emotional beats, and deeper descriptive texture.
  agent: scene_enhancer
  context:
    - chapter_writing
  output_file: draft/enhanced_scenes.md
  markdown: true

continuity_review:
  description: >
    Audit the manuscript for consistency of plot logic, tone, character evolution, and factual/world details. Cross-check all narrative elements and flag or fix any breaks or contradictions.
  expected_output: >
    A continuity report and corrected manuscript draft highlighting changes, areas of concern, and a summary of all resolved issues.
  agent: continuity_supervisor
  context:
    - chapter_writing
    - scene_enhancement
  output_file: draft/continuity_report.md
  markdown: true

on_demand_fact_check:
  description: >
    Answer specific fact or background questions from the writing team during draft and scene development; clarify technical, cultural, historical, or procedural details needed for manuscript authenticity.
  expected_output: >
    A live answer file with direct responses to writer queries, sources, brief explanations, and notes on open questions.
  agent: writing_researcher
  output_file: draft/team_facts.md
  markdown: true
