genre_analysis:
  description: >
    Deeply analyze the concept for genre alignment, examining genre-defining tropes, emerging trends, and successful comparable works. Recommend genre, subgenre, conventions, and audience targeting angles for high market impact.
  expected_output: >
    A genre report detailing primary genre selection, rising conventions, key plot/cast elements, audience trends, and comp title comparisons.
  agent: genre_analyst
  output_file: ideation/genre_report.md
  markdown: true 
  create_directory: true 

plot_structuring:
  description: >
    Build a comprehensive story outline using proven frameworks, mapping acts, chapters, and story beats. Integrate protagonist goals, reversals, midpoint shifts, climaxes, and resolve subplots with strong pacing and emotional payoff.
  expected_output: >
    A plot outline that details act-by-act and chapter-by-chapter breakdowns, lists major and minor beats, and highlights points of tension.
  agent: plot_architect
  context:
    - genre_analysis
  output_file: ideation/plot_outline.md
  markdown: true

character_design:
  description: >
    Create multidimensional characters with authentic emotional core, complex motivations, and compelling arcs. Include detailed bios, transformation journeys, voice notes, and character relationships.
  expected_output: >
    A character bible featuring complete backgrounds, main/secondary motivations, strengths/weaknesses, arc summaries, and key relationship maps.
  agent: character_designer
  context:
    - genre_analysis
    - plot_structuring
  output_file: ideation/character_bible.md
  markdown: true

world_building:
  description: >
    Design an immersive world aligned with the story’s genre and themes. Detail geography, politics, cultures, lore, technologies, and social orders that provide realism and narrative potential.
  expected_output: >
    A world-building dossier outlining major settings, cultures, systems, technologies/magic, environment, and relevant history.
  agent: world_builder
  context:
    - genre_analysis
    - plot_structuring
  output_file: ideation/world_guide.md
  markdown: true

story_research:
  description: >
    Provide in-depth thematic and factual research to ground the story. Supply relevant history, science, cultural practices, or legal background for plot or setting, and flag areas needing further detail.
  expected_output: >
    A curated research file with relevant summaries, citations, annotated facts, and notes on potential story risks or opportunities.
  agent: subject_matter_researcher
  context:
    - genre_analysis
    - plot_structuring
    - world_building
  output_file: ideation/story_research.md
  markdown: true
